version: '3.8'

services:
  fastapi_app:
    build: .
    ports:  
      - "8000:8000"
    volumes:
        - ./features:/app/features
    environment:
        - PYTHONUNBUFFERED=1
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload