name: Test.Ai CI - Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]

    steps:
    #Setup
    - uses: actions/checkout@v4
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verificar versão do Python
      run: python --version

    - name: Rodar testes (exemplo com pytest)
      run: |
        if [ -f pytest.ini ] || [ -d tests ]; then pytest; else echo "Sem testes configurados."; fi
