name: Test.Ai CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    # Configuração do Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    # Instalar dependências
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Instalar flake8 para verificar a qualidade do código
    - name: Instalar flake8
      run: |
        pip install flake8

    # Verificar qualidade do código com flake8 (ignorando erros específicos)
    - name: Verificar qualidade do código com flake8
      run: |
        flake8 . --ignore=E501,W503


