name: Test.Ai CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # CI - Testes e verificação
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    # Configuração do Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    # Instalar dependências
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Verificar se pytest está instalado
    - name: Verificar pytest
      run: |
        pip show pytest

    # Rodar testes com pytest
    - name: Rodar testes com pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q
